apiVersion: v2
name: feast-python-server
description: Feast Feature Server in Python
type: application
version: 0.20.2
keywords:
  - machine learning
  - big data
  - mlops
home: https://feast.dev/
sources:
  - https://github.com/feast-dev/feast
